### PR TITLE
300 url safe panel paths

### LINKED ISSUE #300: 404 when trying to edit or remove path containing a slash
hi everyone,

i just realized that when i have a path with a slash,  lets say 

blog-referenzen/(:all)

or

de/uebermich

that i am redirecting, it works fine, but when i try to either remove or edit them in the panel the popup/modal does not open and i get redirected to 404, so i have to delete them by hand in the yaml

--

## Steps to reproduce

1. setup a path with a slash to be redirected somewhere
2. after saving it, try to edit it

## Expected behavior

modal opens up and you can edit (or delete) the entry

## Additional context

routes-error

## Context

- Browser: latest FF and Chrome
- Kirby version: 3.6.2
- Retour version: 4.0.0

### PR DESCRIPTION
**Pull request by jens-aggergren**
Fixes #300

Depending on the settings, the webserver might not always handle escaped forward-slashes in the way, which this plugin expects it to.

This specifically results in a 404 when trying to edit a redirect-entry, unless the ```AllowEncodedSlashes NoDecode``` is set for the Apache Server. The problem also occurs in relation to nginx.

Many hosting solutions does not allow customers to change such settings for the web-server, and so another solution is required.

## Proposed Changes
  - Replace forward-slash with the non-visible ascii-characer "GROUP-SEPARATOR" (Oct: 035, Dec: 29, Hex: 1D). By using a non-visible character we ensure that the id generation from redirect pattern is always unique.
  - In ```src/panel/components/Tabs/RedirectsTab.vue```, change the dialog route accordingly.
  - In ```src/classes/Redirect.php```, the value returned from the ```id()``` method is changed accordingly.

## Futher remarks
This pull request includes an additional commit, which fixes a unit-test problem. This problem appears to be unrelated to the any to the changes in this pull request. The compiled index.js and index.css have also been commited

### CODE REVIEW

**Comment by basemod** [comment]
This fixes an issue when there is more than one slash in the URL that is to be redirected.

**Comment by bogdancondorachi** [comment]
I can confirm that this solves the issue on my setup as well. Thanks @jens-aggergren

**Comment by distantnative** [comment]
Thanks a lot 🙏🙏🙏

**Comment by jens-aggergren** [comment]
> 

You're very welcome. And thanks for making this very useful plugin in the first place.

**Pull request merged**
