### PR TITLE
Resolving sqlite syntax error with an in-php approach

### LINKED ISSUE #298: Version 4.0.0 causes error when opening redirects page in panel
## Describe the bug

When I install Retour for Kirby 4.0.0 on a site with Kirby version 3.6.2, I can't open the redirects page in the panel.
It's giving me the following error in a popup: `Call to a member function toArray() on bool` 

Also request to the redirects page fails and gives a 500 status code without any specific error.

## Steps to reproduce

1. Install Retour for Kirby using Composer
2. Go to the panel and click on the Redirects button

## Expected behavior
That the redirects page will show.

## Additional context
- The Kirby CMS uses the Dutch language as the default language.

E.g. screenshots
Screenshot 2022-03-03 at 13 54 39
Screenshot 2022-03-03 at 13 47 46

## Context

- Browser: Chrome 98
- Kirby version: 3.6.2
- Retour version: 4.0.0
- Retour config: /

### PR DESCRIPTION
**Pull request by gerricom**
Fixes #298

## Proposed Changes

Older versions of sqlite are not able to perform recursive-selects. Therefore the handy selection of date intervals can't be done within sqlite. I used a different approach and first created an array with the selected steps and joining this with the sql result later.

The code might not be the cleanest yet - please let me know if I can do some things better.

We are currently using this approach live already and it works as intended.

### CODE REVIEW

**Comment by distantnative** [comment]
@gerricom 

How big are your data sets you're using it with? Before I came up with this SQLite solution, I had something in PHP but it would get super slow with a lot of data looking at the timeframe of a year.

**Comment by gerricom** [comment]
Good point. We only have some 3.000 records per year in the table (currently dating back to 2020 around ~10.000 records in total). At the moment this is no problem. 

The question is where performance problems could occure. The proposed approach has roughly three steps: 

- Aggregating a step for the selected step range: That should be as fast as possible relying on the date functions and a simple loop
- The heavy lifting is the sql statement where results are collected and grouped into corresponding steps. For big datasets I suppose this to take time
- Merging the steps and the query's results is the last part and this will at worst iterate steps x results times. That shouldn't be that bad, but for a year this could mean 365 steps x 365 grouped results = 133.225 iterations. But those are only pushing elements into the final array so no heavy computing takes place here...

To speed up the query it might be wise to add an index on the date column.

**Comment by distantnative** [comment]
Sorry for the massive delay here... I will take a closer look again once I've wrapped up Retour 5 for Kirby 4.

**Comment by distantnative** [comment]
I finally took a closer look. Performance-wise it seems to hold up with a couple thousand entries.

But unfortunately the results don't add up 1:1 - there are a couple of % differences in the reported data. So now the question is if the sqlite or the PHP version is actually the correct one.

**Comment by distantnative** [comment]
I've created a PR with my adapted version for Retour 5: https://github.com/distantnative/retour-for-kirby/pull/325

**Comment by distantnative** [comment]
I think the difference seems to be that the PHP version doesn't capture the last step. See the drop in the chart vs. the sqlite version:

Screenshot 2023-09-04 at 22 20 21

Screenshot 2023-09-04 at 22 20 31

**Comment by distantnative** [comment]
Found a fix, will merge the new PR. Thanks a lot!

**Comment by gerricom** [comment]
Thanks! :)

**Comment by distantnative** [comment]
@gerricom Interestingly with really big dataset the new PHP way seems to be even faster.

**Comment by gerricom** [comment]
I guess this is because SQLite can not rely on any index for aggregating our wanted data and therefore needs to perform a full table scan twice - first to select and format the dates and a second time to ask for the results. With the php approach we kill one of those selects and are doing the rest in memory with fast hash lookups... so yes, this could be faster indeed...

**Pull request closed without merging**
