### PR TITLE
Work in progress: V4

### PR DESCRIPTION
**Pull request by distantnative**

### CODE REVIEW

**Comment by johannschopplich** [comment]
This looks so good. Can't wait to use! (Generic statement, but true.)

One idea: what about introducing an option to save redirects as JSON? Yaml seems to be more performance-intense than parsing JSON. I guess not many people are editing the `redirects.yml` by hand. What do you think? 

I admit I have "patched" `Retour.php` to use JSON already. 😇

**Comment by distantnative** [comment]
I get it could be sufficient already to remove the explicit data type from https://github.com/distantnative/retour-for-kirby/blob/v4/src/models/Config.php#L31 - the `Data` class should autodetect it. So if you then set `distant native.retour.config` to something ending in `.json` that would work. Something to try out.

**Comment by distantnative** [comment]
@johannschopplich at the bottom of https://github.com/distantnative/retour-for-kirby/releases/tag/4.0.0-beta.1 you will find how to switch to JSON support in v4

**Comment by johannschopplich** [comment]
Thank you. Happy Easter!

**Pull request merged**
